language: node_js
node_js:
  - '0.12'
before_script:
  - npm install gulp -g
  - gulp tsd
  - node ./node_modules/typescript/bin/tsc -p ./src
  - gulp bundle-css
after_success:
  - sudo apt-get install python
  - sudo ./deploy.sh
